import { readFileSync, writeFileSync } from "node:fs";
import solc from "solc";

const sources = {
  "sCRITToken.sol": { content: readFileSync("contracts/sCRITToken.sol", "utf8") },
  "sCRITLauncher.sol": { content: readFileSync("contracts/sCRITLauncher.sol", "utf8") },
};

const input = {
  language: "Solidity",
  sources,
  settings: {
    optimizer: { enabled: true, runs: 200 },
    outputSelection: { "*": { "*": ["abi", "evm.bytecode.object"] } },
  },
};

const out = JSON.parse(solc.compile(JSON.stringify(input)));
const errors = (out.errors ?? []).filter((e) => e.severity === "error");
if (errors.length > 0) {
  for (const e of errors) console.error(e.formattedMessage);
  process.exit(1);
}

const token = out.contracts["sCRITToken.sol"]["sCRITToken"];
const launcher = out.contracts["sCRITLauncher.sol"]["sCRITLauncher"];

const ts = `// GENERATED by scripts/compile.mjs — do not edit.
export const SCRIT_SOLC_VERSION = "0.8.26";
export const SCRIT_ABI = ${JSON.stringify(token.abi)} as const;
export const SCRIT_BYTECODE = "0x${token.evm.bytecode.object}";
export const SCRIT_LAUNCHER_ABI = ${JSON.stringify(launcher.abi)} as const;
export const SCRIT_LAUNCHER_BYTECODE = "0x${launcher.evm.bytecode.object}";
`;
writeFileSync("lib/scrit-artifact.ts", ts);
console.log("wrote lib/scrit-artifact.ts");
