import { readFileSync, writeFileSync } from "node:fs";
import solc from "solc";

const sources = {
  "sCRITToken.sol": { content: readFileSync("contracts/sCRITToken.sol", "utf8") },
  "sCRITLauncher.sol": { content: readFileSync("contracts/sCRITLauncher.sol", "utf8") },
  "ScritIndexToken.sol": { content: readFileSync("contracts/ScritIndexToken.sol", "utf8") },
  "CustodianRegistry.sol": { content: readFileSync("contracts/CustodianRegistry.sol", "utf8") },
  "PriceOracleAdapter.sol": { content: readFileSync("contracts/PriceOracleAdapter.sol", "utf8") },
  "ReserveManager.sol": { content: readFileSync("contracts/ReserveManager.sol", "utf8") },
  "PhysicalLotToken.sol": { content: readFileSync("contracts/PhysicalLotToken.sol", "utf8") },
  "LotMarketplace.sol": { content: readFileSync("contracts/LotMarketplace.sol", "utf8") },
  "KycRegistry.sol": { content: readFileSync("contracts/KycRegistry.sol", "utf8") },
  "PhysicalLotManager.sol": { content: readFileSync("contracts/PhysicalLotManager.sol", "utf8") },
  "LotRedemptionManager.sol": { content: readFileSync("contracts/LotRedemptionManager.sol", "utf8") },
  "ScritTimelockController.sol": { content: readFileSync("contracts/ScritTimelockController.sol", "utf8") },
  "TradingTaxHook.sol": { content: readFileSync("contracts/TradingTaxHook.sol", "utf8") },
  "sCRITV4Launcher.sol": { content: readFileSync("contracts/sCRITV4Launcher.sol", "utf8") },
  "ScritCreate2Deployer.sol": { content: readFileSync("contracts/ScritCreate2Deployer.sol", "utf8") },
  "DemoSwapHelper.sol": { content: readFileSync("contracts/DemoSwapHelper.sol", "utf8") },
};

const input = {
  language: "Solidity",
  sources,
  settings: {
    optimizer: { enabled: true, runs: 200 },
    viaIR: true,
    evmVersion: "shanghai",
    outputSelection: { "*": { "*": ["abi", "evm.bytecode.object", "evm.deployedBytecode.object"] } },
  },
};

const out = JSON.parse(solc.compile(JSON.stringify(input), {
  import(path) {
    if (path.startsWith("@openzeppelin/") || path.startsWith("@uniswap/")) {
      try { return { contents: readFileSync(`node_modules/${path}`, "utf8") }; }
      catch { return { error: `Unable to resolve ${path}` }; }
    }
    const local = path.replace(/^\.\//, "");
    if (sources[local]) return { contents: sources[local].content };
    return { error: `Unable to resolve ${path}` };
  },
}));
const errors = (out.errors ?? []).filter((e) => e.severity === "error");
if (errors.length > 0) {
  for (const e of errors) console.error(e.formattedMessage);
  process.exit(1);
}

for (const [file, name] of [["TradingTaxHook.sol", "TradingTaxHook"], ["sCRITV4Launcher.sol", "sCRITV4Launcher"]]) {
  const bytes = out.contracts[file][name].evm.deployedBytecode.object.length / 2;
  if (bytes > 24_576) throw new Error(`${name} runtime bytecode exceeds the EIP-170 contract size limit (${bytes} bytes).`);
  console.log(`${name} runtime bytecode: ${bytes} bytes`);
}

const token = out.contracts["sCRITToken.sol"]["sCRITToken"];
const launcher = out.contracts["sCRITLauncher.sol"]["sCRITLauncher"];
const exportArtifact = (name, contract) => `export const ${name}_ABI = ${JSON.stringify(contract.abi)} as const;\nexport const ${name}_BYTECODE = "0x${contract.evm.bytecode.object}";`;
const v2Artifacts = [
  exportArtifact("SCRIT_INDEX", out.contracts["ScritIndexToken.sol"]["ScritIndexToken"]),
  exportArtifact("SCRIT_CUSTODIANS", out.contracts["CustodianRegistry.sol"]["CustodianRegistry"]),
  exportArtifact("SCRIT_PRICES", out.contracts["PriceOracleAdapter.sol"]["PriceOracleAdapter"]),
  exportArtifact("SCRIT_RESERVE", out.contracts["ReserveManager.sol"]["ReserveManager"]),
  exportArtifact("SCRIT_LOT_TOKEN", out.contracts["PhysicalLotToken.sol"]["PhysicalLotToken"]),
  exportArtifact("SCRIT_LOT_MANAGER", out.contracts["PhysicalLotManager.sol"]["PhysicalLotManager"]),
  exportArtifact("SCRIT_LOT_MARKET", out.contracts["LotMarketplace.sol"]["LotMarketplace"]),
  exportArtifact("SCRIT_KYC", out.contracts["KycRegistry.sol"]["KycRegistry"]),
  exportArtifact("SCRIT_LOT_REDEMPTION", out.contracts["LotRedemptionManager.sol"]["LotRedemptionManager"]),
  exportArtifact("SCRIT_TIMELOCK", out.contracts["ScritTimelockController.sol"]["ScritTimelockController"]),
  exportArtifact("SCRIT_TAX_HOOK", out.contracts["TradingTaxHook.sol"]["TradingTaxHook"]),
  exportArtifact("SCRIT_LAUNCHER_V4", out.contracts["sCRITV4Launcher.sol"]["sCRITV4Launcher"]),
  exportArtifact("SCRIT_CREATE2_DEPLOYER", out.contracts["ScritCreate2Deployer.sol"]["ScritCreate2Deployer"]),
  exportArtifact("SCRIT_DEMO_SWAP", out.contracts["DemoSwapHelper.sol"]["DemoSwapHelper"]),
].join("\n");

const ts = `// GENERATED by scripts/compile.mjs — do not edit.
export const SCRIT_SOLC_VERSION = "${solc.version().split("+")[0]}";
export const SCRIT_ABI = ${JSON.stringify(token.abi)} as const;
export const SCRIT_BYTECODE = "0x${token.evm.bytecode.object}";
export const SCRIT_LAUNCHER_ABI = ${JSON.stringify(launcher.abi)} as const;
export const SCRIT_LAUNCHER_BYTECODE = "0x${launcher.evm.bytecode.object}";
${v2Artifacts}
`;
writeFileSync("lib/scrit-artifact.ts", ts);
console.log("wrote lib/scrit-artifact.ts");
